name: C/C++ CI

on:
  push:
    branches: [ "main", "joss2", "dev" ]
  pull_request:
    branches: [ "main", "joss2", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: comua/aerobus-open-source:build-1.2

    steps:
    - uses: actions/checkout@v4
    - name: cppcheck
      if: success()
      run: cppcheck --std=c++20 --language=c++ src/aerobus.h && cppcheck --std=c++20 --language=c++ src/lib_tests.cpp
    - name: cpplint
      if: success()
      run: cpplint src/lib.h && cpplint src/lib_tests.cpp
    - name: test
      if: success()
      run: make clean tests
    - name: documentation
      if: success()
      run: make doc
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # This should be the path to the paper within your repo.
          paper-path: paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: paper.pdf
