name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install compilers and lib
      run: sudo apt-get install -y clang g++ libomp-dev
    - name: make
      run: cd src && make build run
